// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3RUaH26LnM4UQ-u6tNpHtKgeHJkYPhcE',
    appId: '1:532025211449:web:2577a4ad18b303508b6be8',
    messagingSenderId: '532025211449',
    projectId: 'greenpulse-daklak',
    authDomain: 'greenpulse-daklak.firebaseapp.com',
    databaseURL: 'https://greenpulse-daklak-default-rtdb.firebaseio.com',
    storageBucket: 'greenpulse-daklak.firebasestorage.app',
    measurementId: 'G-EG3YZQ17NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB0-XqDXO-g9unbe6zYPJEJ80l76YrLLU',
    appId: '1:532025211449:android:1583822d9b217e658b6be8',
    messagingSenderId: '532025211449',
    projectId: 'greenpulse-daklak',
    databaseURL: 'https://greenpulse-daklak-default-rtdb.firebaseio.com',
    storageBucket: 'greenpulse-daklak.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCZpJNe8WhA4JaBSc8eUD05DX114Wvx0',
    appId: '1:532025211449:ios:a97de3dd9e8bb5148b6be8',
    messagingSenderId: '532025211449',
    projectId: 'greenpulse-daklak',
    databaseURL: 'https://greenpulse-daklak-default-rtdb.firebaseio.com',
    storageBucket: 'greenpulse-daklak.firebasestorage.app',
    iosBundleId: 'com.example.greenpulse',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiCZpJNe8WhA4JaBSc8eUD05DX114Wvx0',
    appId: '1:532025211449:ios:a97de3dd9e8bb5148b6be8',
    messagingSenderId: '532025211449',
    projectId: 'greenpulse-daklak',
    databaseURL: 'https://greenpulse-daklak-default-rtdb.firebaseio.com',
    storageBucket: 'greenpulse-daklak.firebasestorage.app',
    iosBundleId: 'com.example.greenpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3RUaH26LnM4UQ-u6tNpHtKgeHJkYPhcE',
    appId: '1:532025211449:web:1cb6a7bb6add2b068b6be8',
    messagingSenderId: '532025211449',
    projectId: 'greenpulse-daklak',
    authDomain: 'greenpulse-daklak.firebaseapp.com',
    databaseURL: 'https://greenpulse-daklak-default-rtdb.firebaseio.com',
    storageBucket: 'greenpulse-daklak.firebasestorage.app',
    measurementId: 'G-015K3HRB96',
  );
}
